import type { Metadata } from 'next'
import '@/app/globals.css'
import Header from '@/app/components/Header.component'
import Footer from '@/app/components/Footer.component'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
